---
- include: check.yml

- include: tmp.yml
  when: icecast_bin.stat.exists == False

- include: dependencies.yml
  when: icecast_bin.stat.exists == False

- include: download.yml
  when: icecast_bin.stat.exists == False

- include: compile.yml
  when: icecast_bin.stat.exists == False

- include: adduser.yml
  when: icecast_bin.stat.exists == False

- include: config.yml

- name: Install Icecast configuration file
  template: 
    src: icecast.xml.j2 
    dest: "{{ icecast_config_file }}"
    owner: "{{ icecast_user }}" 
    group: "{{ icecast_group }}"  
    mode: 0640
  notify: 
    - reload icecast

- name: Enable Icecast service
  service:
    name: icecast
    enabled: yes
